/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:279ef0ec-a817-4e4c-8ff3-b76e50bb819c",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_VdC53ZiTb",
    "aws_user_pools_web_client_id": "5utbrv9tabsncmtlmdf2sk5ggh",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "region": "eu-north-1",
        "userPoolId": "eu-north-1_CpsDV93sc",
        "userPoolWebClientId": "59lr619rku2dcjkpccpdoadiei",
        "mandatorySignIn": true,
        "authenticationFlowType": "USER_SRP_AUTH"
    }
};


export default awsmobile;
